#### CONFIGURACIÓN DE CONEXIÓN PARA LIQUIBASE ####
changeLogFile=db/changelog-master.yaml
url=jdbc:postgresql://localhost:5432/veterinaria_db
username=carlos_admin
password=MasterPassword2026
driver=org.postgresql.Driver